architecture:
  name: experimental.mace

  model:
    cutoff: 5.0
    cutoff_width: 0.5 
    num_bessel: 8
    num_polynomial_cutoff: 5
    max_ell: 3
    # interaction_cls: "MACEInteraction"
    # interaction_cls_first: "MACEInteractionFirst"
    num_interactions: 3
    hidden_irreps: "64x0e + 64x1o + 64x2e"
    MLP_irreps: "20x0e"
    avg_num_neighbors: 12
    correlation: 3

  training:
    distributed: false
    distributed_port: 39591
    batch_size: 16
    num_epochs: 10000
    num_epochs_warmup: 100
    learning_rate: 1e-4
    weight_decay: null
    scheduler_patience: 250
    log_interval: 1
    checkpoint_interval: 100
    scale_targets: false
    fixed_composition_weights: {}
    per_structure_targets: []
    log_mae: true
    log_separate_blocks: false
    best_model_metric: rmse_prod
    grad_clip_norm: .inf
    loss:
      type: mse
      weights: {}
      reduction: mean
      sliding_factor: null
