coverage:
  range: "60...80"
  status:
    project:
      default: false

      # core package
      core:
        target: 88%
        paths:
          - "src/metatrain/utils/.*"
          - "src/metatrain/cli/.*"

    patch:
      default:
        informational: true

component_management:
  individual_components:

    # stable architectures
    - component_id: gap
      name: GAP
      paths:
        - "src/metatrain/gap/.*"

    - component_id: soap_bpnn
      name: SOAP-BPNN
      paths:
        - "src/metatrain/soap_bpnn/.*"

    - component_id: pet
      name: PET
      paths:
        - "src/metatrain/pet/.*"

    - component_id: llpr
      name: LLPR
      paths:
        - "src/metatrain/llpr/.*"

    # experimental architectures
    - component_id: flashmd
      name: FlashMD
      paths:
        - "src/metatrain/experimental/flashmd/.*"

    - component_id: classifier
      name: Classifier
      paths:
        - "src/metatrain/experimental/classifier/.*"

    - component_id: mace
      name: MACE
      paths:
        - "src/metatrain/experimental/mace/.*"

    - component_id: phace
      name: PhACE
      paths:
        - "src/metatrain/experimental/phace/.*"

ignore:
  # no need to report coverage of the test code themself
  - "src/metatrain/utils/testing/.*"
  - "src/metatrain/.*/tests/.*"
  # we don't currently run distributed tests on CI
  - "src/metatrain/utils/distributed/.*"
  # auto-generated
  - "src/metatrain/_version.py"

comment: false
