architecture:
  name: soap_bpnn

  model:
    soap:
      cutoff:
        radius: 5.0
        smoothing: 
          type: ShiftedCosine
          width: 1.0
      density:
        type: Gaussian
        center_atom_weight: 1.0
        width: 0.3
        scaling:
          type: Willatt2018
          rate: 1.0
          scale: 2.0
          exponent: 7.0
      basis:
        type: TensorProduct
        max_angular: 6
        radial:
          type: Gto
          max_radial: 7
    bpnn:
      layernorm: true
      num_hidden_layers: 2
      num_neurons_per_layer: 32
    heads: {}
    zbl: false

  training:
    distributed: False
    distributed_port: 39591
    batch_size: 8
    num_epochs: 100
    learning_rate: 0.001
    early_stopping_patience: 200
    scheduler_patience: 100
    scheduler_factor: 0.8
    log_interval: 5
    checkpoint_interval: 25
    scale_targets: true
    fixed_composition_weights: {}
    per_structure_targets: []
    log_mae: False
    log_separate_blocks: false
    best_model_metric: rmse_prod
    loss:
      type: mse
      weights: {}
      reduction: mean
