architecture:
  name: soap_bpnn
  model:
    soap:
      max_angular: 6
      max_radial: 7
      cutoff:
        radius: 5.0
        width: 0.5
    bpnn:
      layernorm: true
      num_hidden_layers: 2
      num_neurons_per_layer: 32
    add_lambda_basis: true
    heads: {}
    zbl: false
    long_range:
      enable: false
      use_ewald: false
      smearing: 1.4
      kspace_resolution: 1.33
      interpolation_nodes: 5
  training:
    distributed: false
    distributed_port: 39591
    batch_size: 8
    num_epochs: 100
    warmup_fraction: 0.01
    learning_rate: 0.001
    log_interval: 5
    checkpoint_interval: 25
    fit_composition_model: true
    scale_targets: true
    fixed_composition_weights: {}
    fixed_scaling_weights: {}
    per_structure_targets: []
    num_workers: null
    log_mae: false
    log_separate_blocks: false
    best_model_metric: rmse_prod
    loss: mse
