name: ✨ Feature request
description: Suggest an idea or improvement.
title: "[FEATURE] "
labels: [Enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Suggest an idea or improvement for this project.
  - type: textarea
    id: problem_description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        A clear and concise description of what the problem is.
        Example: "I'm always frustrated when [...]"
      placeholder: Describe the problem you are facing or the motivation for the feature.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the ideal solution or feature you would like to see.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Mention any workarounds or alternative ideas you have explored.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Provide links, images, or related discussions if available.
    validations:
      required: false
