architecture:
  name: experimental.phace 
  
  model:
    nu_max: 3
    num_message_passing_layers: 2
    cutoff: 5.0
    cutoff_width: 1.0
    num_element_channels: 64
    radial_basis:
      mlp: true
      E_max: 50.0
      scale: 0.7
      optimizable_lengthscales: false
    nu_scaling: 0.1
    mp_scaling: 0.1
    overall_scaling: 1.0
    disable_nu_0: True
    use_sphericart: False
    heads: {}
    zbl: False

  training:
    distributed: False
    distributed_port: 39591
    batch_size: 8
    num_epochs: 1000
    learning_rate: 0.01
    gradient_clipping: null
    scheduler_patience: 100
    scheduler_factor: 0.7
    log_interval: 1
    checkpoint_interval: 25
    scale_targets: true
    fixed_composition_weights: {}
    per_structure_targets: []
    log_mae: False
    loss:
      type: mse
      weights: {}
      reduction: sum
    best_model_metric: rmse_prod
