architecture:
  name: experimental.phace
  model:
    max_correlation_order_per_layer: 3
    num_message_passing_layers: 2
    cutoff: 5.0
    cutoff_width: 1.0
    num_element_channels: 64
    radial_basis:
      mlp: true
      max_eigenvalue: 30.0
      scale: 0.7
      optimizable_lengthscales: false
    nu_scaling: 0.1
    mp_scaling: 0.1
    overall_scaling: 1.0
    disable_nu_0: true
    use_sphericart: false
    head_num_layers: 1
    heads: {}
    zbl: false
  training:
    distributed: false
    distributed_port: 39591
    batch_size: 8
    num_epochs: 1000
    learning_rate: 0.01
    warmup_fraction: 0.01
    gradient_clipping: null
    scheduler_patience: 100
    scheduler_factor: 0.7
    log_interval: 1
    checkpoint_interval: 25
    scale_targets: true
    fixed_composition_weights: {}
    fixed_scaling_weights: {}
    num_workers: null
    per_structure_targets: []
    log_separate_blocks: false
    log_mae: false
    loss:
      type: mse
      weights: {}
      reduction: sum
    best_model_metric: rmse_prod
