architecture:
  name: experimental.phace 
  
  model:
    nu_max: 3
    num_message_passing_layers: 2
    cutoff: 5.0
    num_element_channels: 8
    radial_basis:
      mlp: true
      E_max: 70.0
      scale: 0.7
    nu_scaling: 1.0
    mp_scaling: 1.0
    disable_nu_0: True
    use_sphericart: False
    heads: {}
    zbl: False

  training:
    distributed: False
    distributed_port: 39591
    batch_size: 8
    num_epochs: 100
    learning_rate: 0.001
    scheduler_patience: 10
    scheduler_factor: 0.8
    log_interval: 10
    checkpoint_interval: 25
    scale_targets: true
    fixed_composition_weights: {}
    per_structure_targets: []
    log_mae: False
    loss:
      type: mse
      weights: {}
      reduction: sum
