model:
  soap:
    num_pseudo_species: 4
    cutoff: 5.0
    basis_cutoff_power_spectrum: 400
    radial_basis_type: 'physical'
    basis_scale: 3.0
    trainable_basis: true
    normalize: true
    contract_center_species: true
  bpnn:
    hidden_sizes: [32, 32]
    output_size: 1

training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.001
  early_stopping_patience: 50
  scheduler_patience: 10
  scheduler_factor: 0.8  
  log_interval: 5
  checkpoint_interval: 25
  per_structure_targets: []
  loss_weights: {}
