device: cpu
base_precision: 64
seed: 42

architecture:
  name: pet
  training:
    batch_size: 1
    num_epochs: 10
    learning_rate: 0.01
    atomic_baseline:
      mtt::dos: 0.0
    scale_targets: false
    loss:
      mtt::dos:
        type: shift_agnostic_mse
        weight: 1.0
        grad_weight: 1e-4
        int_weight: 2
        reduction: mean

# Section defining the parameters for system and target data
training_set:
  systems: DOS.xyz
  targets:
    mtt::dos:
      key: dos
      sample_kind: system
      type: scalar
      num_subtargets: 3630

validation_set:
  systems: DOS.xyz
  targets:
    mtt::dos:
      key: dos
      sample_kind: system
      type: scalar
      num_subtargets: 3630

test_set: 0.0
