seed: 42
base_precision: 32

architecture:
  name: experimental.flashmd_symplectic
  training:
    timestep: 32  # in this case 32 (time lag) * 1 fs (timestep of reference MD)
    batch_size: 8  # to be increased in a production scenario
    num_epochs: 3  # to be increased (at least 1000-10000) in a production scenario
    log_interval: 1
    learning_rate: 3e-4
    # Note that the scaling weights should be set to the same values to prevent
    # inconsistencies in the loss function. Look at the field documentation 
    # for further details.
    fixed_scaling_weights:
      positions: 1.0
      momenta: 1.0
    loss: mse

training_set:
  systems:
    read_from: midpoint-to-delta.xyz
    length_unit: A
  targets:
    positions:
      key: delta_positions
      quantity: length
      unit: A
      type:
        cartesian:
          rank: 1
      per_atom: true
    momenta:
      key: delta_momenta
      quantity: momentum
      unit: (eV*u)^(1/2)
      type:
        cartesian:
          rank: 1
      per_atom: true

validation_set: 0.1
test_set: 0.0
