architecture:
  name: pet
  model:
    cutoff: 4.5
  training:
    distributed: true  # switch on distributed training mode
    num_epochs: 100  # increased to 100 to compare with non-distributed
    batch_size: 10
    log_interval: 1
    checkpoint_interval: 10

training_set:
  systems:
    read_from: ethanol_reduced_100.xyz
    length_unit: Angstrom
  targets:
    energy:
      key: energy
      unit: eV

test_set: 0.1
validation_set: 0.1
