seed: 42

architecture:
  name: soap_bpnn
  training:
    batch_size: 8
    num_epochs: 100
    log_interval: 1

training_set:
  systems:
    read_from: train.xyz
    length_unit: angstrom
  targets:
    energy:
      key: energy
      unit: eV

validation_set:
  systems:
    read_from: valid.xyz
    length_unit: angstrom
  targets:
    energy:
      key: energy
      unit: eV

test_set:
  systems:
    read_from: test.xyz
    length_unit: angstrom
  targets:
    energy:
      key: energy
      unit: eV
