architecture:

  name: experimental.mlelec

  model:
    node:
      cutoff:
        radius: 5.0
        smoothing: 
          type: ShiftedCosine
          width: 1.0
      density:
        type: Gaussian
        center_atom_weight: 1.0
        width: 0.3
        scaling:
          type: Willatt2018
          rate: 1.0
          scale: 2.0
          exponent: 7.0
      basis:
        type: TensorProduct
        max_angular: 3
        radial:
          type: Gto
          max_radial: 3
    edge:
      cutoff:
        radius: 6.0
        smoothing: 
          type: ShiftedCosine
          width: 1.0
      density:
        type: Gaussian
        center_atom_weight: 1.0
        width: 0.3
        scaling:
          type: Willatt2018
          rate: 1.0
          scale: 2.0
          exponent: 7.0
      basis:
        type: TensorProduct
        max_angular: 1
        radial:
          type: Gto
          max_radial: 3

  training:
    distributed: False
    distributed_port: 39591
    batch_size: 16
    num_epochs: 10000
    learning_rate: 3e-4
    scheduler_patience: 100
    scheduler_factor: 0.8
    early_stopping_patience: 200
    log_interval: 10
    checkpoint_interval: 100
    scale_targets: true
    fixed_composition_weights: {}
    per_structure_targets: []
    log_mae: False
    log_separate_blocks: false
    best_model_metric: rmse_prod
    loss:
      type: mse
      weights: {}
      reduction: mean
