include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - test

test_job:
  stage: test
  extends: .container-runner-daint-gh200
  image: nvcr.io/nvidia/pytorch:24.12-py3
  timeout: 2h
  script:
    - export CUDA_HOME="/usr/local/cuda"
    - apt-get update && apt-get install -y libfftw3-dev
    - python3 -m pip install --upgrade pip
    - python3 -m pip install tox
    - tox

  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_PARTITION: normal
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: '02:30:00'
    GIT_STRATEGY: fetch
