FROM docker://nvcr.io/nvidia/pytorch:24.12-py3

RUN apt update && \
	apt install -y libfftw3-dev && \
	apt clean

RUN which python && python -V && \
  	python -m pip install --upgrade pip && \
	python -m pip install tox pytest pytest-cov pytest-xdist

ENV CUDA_HOME="/usr/local/cuda"
