FROM docker://nvcr.io/nvidia/pytorch:24.12-py3

RUN apt update && \
	apt install -y libfftw3-dev && \
	apt clean

RUN python3 -m pip install --upgrade pip && \
	python3 -m pip install tox

ENV CUDA_HOME="/usr/local/cuda"
