ARG BASE_IMAGE
FROM $BASE_IMAGE

# Copy metatrain repository within the container
# The repo is cloned by CI (GIT_STRATEGY: clone)
COPY . /metatrain/

RUN python3 -m venv /mtt-venv && \
	. /mtt-venv/bin/activate && \
	python -m pip install torch==2.7.1+cu128 /metatrain[soap-bpnn]
