architecture:
  name: mlip_example
  model:
    cutoff: 5.0
  training:
    distributed: false
    distributed_port: 39591
    batch_size: 8
    num_epochs: 10
    warmup_fraction: 0.01
    learning_rate: 0.001
    log_interval: 5
    checkpoint_interval: 5
    scale_targets: true
    fixed_composition_weights: {}
    fixed_scaling_weights: {}
    per_structure_targets: []
    num_workers: null
    log_mae: false
    log_separate_blocks: false
    best_model_metric: rmse_prod
    loss: mse
