architecture:
  name: experimental.flashmd
  model:
    predict_difference_of_momenta: false
    cutoff: 5.0
    cutoff_width: 0.5
    d_pet: 128
    d_head: 128
    d_feedforward: 512
    num_heads: 4
    num_attention_layers: 2
    num_gnn_layers: 2
    long_range:
      enable: false
      smearing: 1.4
      interpolation_nodes: 5
      mesh_spacing: 1.33
  training:
    masses: {}
    distributed: false
    distributed_port: 39591
    batch_size: 16
    num_epochs: 1000
    warmup_fraction: 0.01
    learning_rate: 3e-4
    weight_decay: null
    log_interval: 10
    checkpoint_interval: 100
    scale_targets: true
    fixed_composition_weights: {}
    fixed_scaling_weights: {}
    per_structure_targets: []
    num_workers: null
    grad_clip_norm: .inf
    log_mae: false
    log_separate_blocks: false
    best_model_metric: rmse_prod
    loss: mse
