name: Merge queue tests

# This file defines tests that will run once per PR, before merging it. We use it to run
# expensive tests before merging code while not running them on every single commit.
on:
  merge_group:

jobs:
  merge-queue-tests:
    name: ${{ matrix.test-name }}
    strategy:
      matrix:
        test-name:
          - tests
          - gap-tests
          - soap-bpnn-tests
          - pet-tests
          - nanopet-tests
          - deprecated-pet-tests

    runs-on: ubuntu-22.04 # TODO replace with a GPU-enabled runner

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install tox

      - name: run Python tests
        run: |
          tox -e ${{ matrix.test-name }}
