name: Release

on:
  push:
    tags: ["*"]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/metatrain
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.0"
        python-version: "3.13"
        enable-cache: true
        activate-environment: true

    - name: Setup dependencies
      run: |
        uv tool install tox --with tox-uv

    - name: Build package
      run: tox -e build
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Publish to GitHub release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.tar.gz
          dist/*.whl
        prerelease: ${{ contains(github.ref, '-rc') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
